### ISSUE TITLE
Merging/Updating Styles

### ISSUE THREAD

**Issue by AvsCode** [maftoun95/helenIC#3]
When we get to needing multiple pages/routes, we should break apart our styles, decouple them from the components themselves and build style files, otherwise our files will become unwieldy.  How we break them apart and group them together needs to be figured out.

**Comment by maftoun95** [comment]
We should do this using css modules. This way we can write one style sheet per route and import at the top of any given component. 

Because of the way create react app is setup, we already have access to this funcionality. 

Additional benefits include getting css weighting back and gaining the code maintainability we are all familiar with. 

Thoughts?
